# Generated by Django 2.0.3 on 2018-10-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181022_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table=None,
        ),
    ]
