# Generated by Django 2.0.3 on 2018-10-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181017_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'verbose_name': '项目图片', 'verbose_name_plural': '项目图片'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Can view project'),), 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('view_task', 'Can view task'),), 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterField(
            model_name='project',
            name='deleting',
            field=models.BooleanField(db_index=True, default=False, help_text='是否删除'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='The person who created the project', on_delete=django.db.models.deletion.PROTECT, to='app.MyUser', verbose_name='所有者'),
        ),
    ]
