# Generated by Django 2.0.3 on 2018-11-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181105_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='/logo512.png', upload_to=''),
        ),
    ]
